/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import domain.Ambalaza;
import domain.Kupac;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JTextField;
import DBBroker.DatabaseBroker;
import Table.ZaduzenjaTableModel;
import domain.Zaduzenje;
import java.awt.event.ItemEvent;
import form.FrmMain;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
/**
 *
 * @author xMx
 */
public class KreirajZaduzenje extends javax.swing.JDialog {
    DatabaseBroker dbbr = new DatabaseBroker();
    
    /**
     * Creates new form KreirajZaduzenje
     */
    public KreirajZaduzenje(JDialog parent, boolean modal,String sifra,String ime_prezime,String jmbg) {
        super(parent, modal);
        
        initComponents();
        setTxtImePrezime(ime_prezime);
        setTxtJMBG(jmbg);
        setTxtSifra(sifra);
        prepareView();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblZaduzenja = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtImePrezime = new javax.swing.JTextField();
        txtJMBG = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboAmbalaze = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JTextField();
        btnZaduzi = new javax.swing.JButton();
        btnRazduzi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNapomena = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Postojeca Zaduzenja"));

        tblZaduzenja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblZaduzenja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblZaduzenjaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblZaduzenja);

        jLabel3.setText("Ime i prezime");

        txtSifra.setEditable(false);

        jLabel4.setText("JMBG");

        jLabel7.setText("Sifra kupca");

        txtImePrezime.setEditable(false);

        txtJMBG.setEditable(false);

        jLabel1.setText("Odaberi Ambalazu");

        jLabel2.setText("Unesi kolicinu");

        btnZaduzi.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnZaduzi.setText("Zaduzi");
        btnZaduzi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnZaduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaduziActionPerformed(evt);
            }
        });

        btnRazduzi.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnRazduzi.setText("Razduzi");
        btnRazduzi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRazduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRazduziActionPerformed(evt);
            }
        });

        btnIzmeni.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnIzmeni.setText("Izmeni");
        btnIzmeni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel5.setText("Napomena:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKolicina, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(comboAmbalaze, 0, 200, Short.MAX_VALUE)
                            .addComponent(txtNapomena, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZaduzi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnRazduzi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboAmbalaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnZaduzi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRazduzi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZaduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaduziActionPerformed
        String kupac_idS = txtSifra.getText();
        Long kupac_id = Long.parseLong(kupac_idS);
        
        String kolicinaText = txtKolicina.getText().trim();
        String napomena = txtNapomena.getText();
         if (kolicinaText.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Unesite količinu!", "Greška", JOptionPane.ERROR_MESSAGE);
    return;
         }
        if (!kolicinaText.matches("-?\\d+")){
            JOptionPane.showMessageDialog(this, "U polju kolicina moze biti prosledjen samo broj", "Error", JOptionPane.ERROR_MESSAGE);
            
            return;
        }
       

        int kolicina = Integer.parseInt(txtKolicina.getText());
        if(kolicina == 0){
            JOptionPane.showMessageDialog(this, "Ne moze se zaduziti 0 kolicina", "Greska", JOptionPane.ERROR_MESSAGE);
        }
        
        
        Ambalaza ambalaza = (Ambalaza) comboAmbalaze.getSelectedItem();
        if(ambalaza == null){
            JOptionPane.showMessageDialog(this, "Nije izabrana ambalaza", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da zaduzite kupca: "+txtImePrezime.getText()+ "\n ambalaza: "+comboAmbalaze.getSelectedItem()+"\n kolicina: "+txtKolicina.getText()+"\nUz napomenu: "+napomena, "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.NO_OPTION){
             return;   
            }
            if(result == JOptionPane.CLOSED_OPTION){
                return;
            }
            else{
        dbbr.ZaduziKupca(kupac_id, ambalaza.getId(), LocalDateTime.now(), kolicina,napomena);
        JOptionPane.showMessageDialog(this, "Zaduznje uspesno izvrseno");
        }
        }
        popuniTabelu();
        txtKolicina.setText("");
    }//GEN-LAST:event_btnZaduziActionPerformed

    private void btnRazduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRazduziActionPerformed
        int selectedRow = tblZaduzenja.getSelectedRow();
        if (selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Nista nije selektovano u tabeli", "Greska", JOptionPane.ERROR_MESSAGE);
        }
        else if(tblZaduzenja.getSelectedRowCount() > 1){
            JOptionPane.showMessageDialog(this, "Moguce je selektovati najvise jedan red", "Greska", JOptionPane.ERROR_MESSAGE);
        }
        else{
         Long id = (Long) tblZaduzenja.getValueAt(selectedRow, 0);
         int kolicina = (int) tblZaduzenja.getValueAt(selectedRow, 3);
        
          
        String ime_prezime = (String) tblZaduzenja.getValueAt(selectedRow, 1);
        String naziv_ambalaze = (String) tblZaduzenja.getValueAt(selectedRow, 2);
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da razduzite kupca: "+ime_prezime+"\n ambalaza: "+naziv_ambalaze+"\n kolicina: "+kolicina+" ?", "Brisanje zaduzenja", JOptionPane.YES_NO_OPTION);
        if(odgovor == JOptionPane.NO_OPTION){
            return;
        }
        if(odgovor == JOptionPane.CLOSED_OPTION){
                return;
            }
        else{
            dbbr.ObrisiZaduzenje(id);
        JOptionPane.showMessageDialog(this, "Uspesno obrisano zaduzenje");
        }
        
        popuniTabelu();
        }
       
        
        
    }//GEN-LAST:event_btnRazduziActionPerformed

    private void tblZaduzenjaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblZaduzenjaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            tblZaduzenja.clearSelection(); // 
        }
    }//GEN-LAST:event_tblZaduzenjaKeyPressed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        String kolicinaText = txtKolicina.getText().trim();
        String napomena = txtNapomena.getText();
         if (kolicinaText.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Unesite količinu!", "Greška", JOptionPane.ERROR_MESSAGE);
    return;
         }
        if (!kolicinaText.matches("-?\\d+")){
            JOptionPane.showMessageDialog(this, "U polju kolicina moze biti prosledjen samo broj", "Error", JOptionPane.ERROR_MESSAGE);
            
            return;
        }
       

        int kolicina = Integer.parseInt(txtKolicina.getText());
        if(kolicina == 0){
            JOptionPane.showMessageDialog(this, "Ne moze se razduziti za 0", "Greska", JOptionPane.ERROR_MESSAGE);
        }
        int selected_row = tblZaduzenja.getSelectedRow();
        if(selected_row == - 1){
            JOptionPane.showMessageDialog(this, "Nista nije selektovano u tabeli", "Greska", JOptionPane.ERROR_MESSAGE);
        }
        
        else if (tblZaduzenja.getSelectedRowCount() > 1){
            JOptionPane.showMessageDialog(this, "Moguce je selektovati najvise jedan red", "Greska", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            Long id_zaduzenja = (Long) tblZaduzenja.getValueAt(selected_row, 0);
            String ime_prezime = (String) tblZaduzenja.getValueAt(selected_row, 1);
            String naziv_ambalaze = (String) tblZaduzenja.getValueAt(selected_row, 2);
            
            int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da prepravite zaduzenje: id "+id_zaduzenja+"\nAmbalaza: "+naziv_ambalaze+"\nIme i Prezime: "+ime_prezime+"\n Umanjiti za kolicinu: "+kolicina+"\nUz napomenu: "+napomena);
            if (odgovor == JOptionPane.NO_OPTION){
                return;
            }
            if (odgovor == JOptionPane.CANCEL_OPTION){
                return;
            }
            if(odgovor == JOptionPane.CLOSED_OPTION){
                return;
            }
            else{
            dbbr.izmeniZaduzenje(id_zaduzenja, kolicina,napomena);
            JOptionPane.showMessageDialog(this, "Uspesno izvrsena izmena");
            txtKolicina.setText("");
        }
        }
        popuniTabelu();
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnRazduzi;
    private javax.swing.JButton btnZaduzi;
    private javax.swing.JComboBox<Ambalaza> comboAmbalaze;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblZaduzenja;
    private javax.swing.JTextField txtImePrezime;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtNapomena;
    private javax.swing.JTextField txtSifra;
    // End of variables declaration//GEN-END:variables

    
    
    public void setTxtSifra(String sifra){
        txtSifra.setText(sifra);
    }
    

    public void setTxtJMBG(String JMBG){
        txtJMBG.setText(JMBG);
        
    }

    public void setTxtImePrezime(String ime_prezime) {
        txtImePrezime.setText(ime_prezime);
        
         txtImePrezime.setEditable(false);
    }

   private String getTxtSifra() {
        return txtSifra.getText();
    }

    private void prepareView(){
        fillAmbalaze();
        popuniTabelu();
        
    }
    
    
    private void fillAmbalaze(){
        List<Ambalaza> ambalaze = new ArrayList<>();
        ambalaze = dbbr.vratiAmbalaze();
        for(Ambalaza a: ambalaze){
            comboAmbalaze.addItem(a);
        }
    }
    
    private void popuniTabelu(){
        List<Zaduzenje> zaduzenja = new ArrayList<>();
        
        zaduzenja = dbbr.vratiZaduzenja(getTxtSifra());
        
        ZaduzenjaTableModel ztm = new ZaduzenjaTableModel(zaduzenja);
        tblZaduzenja.setModel(ztm);
        
       
    }

    

    
   
}
