/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;
import DBBroker.DatabaseBroker;
import domain.Ambalaza;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
import Table.AmbalazaTableModel;

/**
 *
 * @author xMx
 */
public class KreirajAmbalazu extends javax.swing.JDialog {
    DatabaseBroker dbbr = new DatabaseBroker();
    /**
     * Creates new form KreirajAmbalazu
     */
    public KreirajAmbalazu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillAmbalaza();
        setTitle("Kreiranje Ambalaze");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtKapacitet = new javax.swing.JTextField();
        btnKreiraj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAmbalaza = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Naziv ambalaze");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Kapacitet");

        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        btnKreiraj.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnKreiraj.setText("Kreiraj");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        tblAmbalaza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAmbalaza);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(txtKapacitet))
                        .addGap(105, 105, 105)
                        .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKapacitet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        String naziv = txtNaziv.getText();
        String strkapacitet = txtKapacitet.getText();
        if(naziv.equals("") || naziv.equals(" ")){
            JOptionPane.showMessageDialog(this, "Unesi naziv ambalaze", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(strkapacitet.equals("")){
            JOptionPane.showMessageDialog(this, "Polje kapacitet je prazno", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!strkapacitet.matches("\\d+")){
            JOptionPane.showMessageDialog(this, "U polje kapacitet mogu se unositi samo cifre", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int kapacitet = Integer.parseInt(strkapacitet);
        
        dbbr.kreirajAmbalazu(naziv, kapacitet);
        JOptionPane.showMessageDialog(this, "Uspesno kreirana ambalaza: "+naziv+" sa kapacitetom od: "+kapacitet, "Kreiranje nove ambalaze", JOptionPane.INFORMATION_MESSAGE);
        txtKapacitet.setText("");
        txtNaziv.setText("");
        fillAmbalaza();
    }//GEN-LAST:event_btnKreirajActionPerformed

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivActionPerformed
        String naziv = txtNaziv.getText();
        List<Ambalaza> ambalaze = new ArrayList<>();
        ambalaze = dbbr.pretraziAmbalaze(naziv);
        AmbalazaTableModel atm = new AmbalazaTableModel(ambalaze);
        tblAmbalaza.setModel(atm);
    }//GEN-LAST:event_txtNazivActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAmbalaza;
    private javax.swing.JTextField txtKapacitet;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

public void fillAmbalaza(){
 
    List<Ambalaza> ambalaze = new ArrayList<>();
    ambalaze = dbbr.vratiAmbalaze();
    AmbalazaTableModel atm = new AmbalazaTableModel(ambalaze);
    tblAmbalaza.setModel(atm);
    
}
    
}
