/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;
import domain.Kupac;
import DBBroker.DatabaseBroker;
import java.util.List;
import java.util.ArrayList;
import Table.KupciTableModel;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
/**
 *
 * @author xMx
 */
public class PretraziKupca extends javax.swing.JDialog {
    private DatabaseBroker dbbr = new DatabaseBroker();
    private FrmMain mainFrame;
    /**
     * Creates new form PretraziKupca
     */
    public PretraziKupca(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        this.mainFrame = mainFrame;
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtJMBG = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKupci = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        btnKreiraj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel3.setText("Pretrazi po JMBG");

        txtJMBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJMBGActionPerformed(evt);
            }
        });

        tblKupci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKupci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblKupciKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblKupci);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel1.setText("Pretrazi po imenu");

        txtIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeActionPerformed(evt);
            }
        });

        btnKreiraj.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnKreiraj.setText("Kreiraj Kupca");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJMBG, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKreiraj)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJMBG, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeActionPerformed
         
        String ime_prezime = txtIme.getText();
        String jmbg = txtJMBG.getText();
        List<Kupac> kupci = new ArrayList<>();
        kupci = dbbr.pretrazi(ime_prezime, jmbg);
        KupciTableModel tm = new KupciTableModel(kupci);
        tblKupci.setModel(tm);
    }//GEN-LAST:event_txtImeActionPerformed

    private void txtJMBGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJMBGActionPerformed
       String ime_prezime = txtIme.getText();
        String jmbg = txtJMBG.getText();
        List<Kupac> kupci = new ArrayList<>();
        kupci = dbbr.pretrazi(ime_prezime, jmbg);
        KupciTableModel tm = new KupciTableModel(kupci);
        tblKupci.setModel(tm);
    }//GEN-LAST:event_txtJMBGActionPerformed

    private void tblKupciKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKupciKeyPressed
        tblKupci.requestFocusInWindow();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            int selectedRow = tblKupci.getSelectedRow();
            if(selectedRow != -1){
                Long idL = (Long) tblKupci.getValueAt(selectedRow, 0);
                String id = String.valueOf(idL);
                String ime_prezime = tblKupci.getValueAt(selectedRow, 1).toString();
                String jmbg = tblKupci.getValueAt(selectedRow, 2).toString();
                String adresa = tblKupci.getValueAt(selectedRow, 3).toString();
                String broj_telefona = tblKupci.getValueAt(selectedRow, 4).toString();
                
                KreirajZaduzenje dialog = new KreirajZaduzenje(this, true,id,ime_prezime,jmbg);
               
                dialog.setTxtImePrezime(ime_prezime);
                dialog.setTxtSifra(id);
                dialog.setTxtJMBG(jmbg);
                
                this.dispose();
                
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
                
                 
                
                 
            }
        }
    }//GEN-LAST:event_tblKupciKeyPressed

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        JFrame main = new FrmMain();
        JDialog dialog = new KreirajKupca(main, true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        DatabaseBroker d = new DatabaseBroker();
        List<Kupac> kupci = new ArrayList<>();
        kupci = d.pretrazi(txtIme.getText(), txtJMBG.getText());
        KupciTableModel ktm = new KupciTableModel(kupci);
        tblKupci.setModel(ktm);
    }//GEN-LAST:event_btnKreirajActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKupci;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    // End of variables declaration//GEN-END:variables

private void prepareView(){
    List<Kupac> kupci = new ArrayList<>();
   kupci = dbbr.vratiKupce();
   KupciTableModel itm = new KupciTableModel(kupci);
   tblKupci.setModel(itm);
}
    




}
