/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;
import java.util.List;
import java.util.ArrayList;
import domain.Ambalaza;
import DBBroker.DatabaseBroker;
import Table.AmbalazaTableModel;
import javax.swing.JDialog;
/**
 *
 * @author xMx
 */
public class PrikazSvihAmbalaza extends javax.swing.JDialog {
    DatabaseBroker dbbr = new DatabaseBroker();
    List<Ambalaza> ambalaze = new ArrayList<>();
    /**
     * Creates new form PrikazSvihAmbalaza
     */
    public PrikazSvihAmbalaza(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniTabelu(ambalaze);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tblAmbalaze = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        scrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Ambalaze"));

        tblAmbalaze.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane.setViewportView(tblAmbalaze);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblAmbalaze;
    // End of variables declaration//GEN-END:variables
    public  void popuniTabelu(List<Ambalaza> amblaze){
     
     ambalaze = dbbr.vratiAmbalaze();
     AmbalazaTableModel atm = new AmbalazaTableModel(ambalaze);
     tblAmbalaze.setModel(atm);
    }
    
    public void prikaziTabelu(List<Ambalaza> ambalaze, String naziv){
        ambalaze = dbbr.pretraziAmbalaze(naziv);
        AmbalazaTableModel atm = new AmbalazaTableModel(ambalaze);
        tblAmbalaze.setModel(atm);
    }
    
}
