/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;

import DBBroker.DatabaseBroker;
import Table.ZbirnoStanjePoAmbalaziTableModel;
import Table.ZbirnoStanjeTableModel;
import domain.ZbirnoStanje;
import domain.ZbirnoStanjePoAmbalazi;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JTextField;

/**
 *
 * @author xMx
 */
public class ZaduzenjaPoAmbalazi extends javax.swing.JDialog {
   
    /**
     * Creates new form ZaduzenjaPoAmbalazi
     */
    public ZaduzenjaPoAmbalazi(JDialog parent, boolean modal,Long id_ambalaze,String naziv_ambalaze) {
        super(parent, modal);
        initComponents();
        setTxtNazivAmbalaze(naziv_ambalaze);
        setTxtSifra(id_ambalaze);
        popuNiTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNazivAmbalaze = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZaduzenjaPoAmbalazi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Zaduzenja po ambalazi:");

        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane1KeyPressed(evt);
            }
        });

        tblZaduzenjaPoAmbalazi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblZaduzenjaPoAmbalazi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblZaduzenjaPoAmbalaziKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblZaduzenjaPoAmbalazi);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Sifra ambalaze");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNazivAmbalaze, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNazivAmbalaze)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSifra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1KeyPressed

    private void tblZaduzenjaPoAmbalaziKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblZaduzenjaPoAmbalaziKeyPressed
        
    }//GEN-LAST:event_tblZaduzenjaPoAmbalaziKeyPressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblZaduzenjaPoAmbalazi;
    private javax.swing.JTextField txtNazivAmbalaze;
    private javax.swing.JTextField txtSifra;
    // End of variables declaration//GEN-END:variables

    public void setTxtNazivAmbalaze(String NazivAmbalaze) {
        this.txtNazivAmbalaze.setText(NazivAmbalaze);
        this.txtNazivAmbalaze.setEditable(false);
    }

    private void popuNiTabelu(){
        List<ZbirnoStanjePoAmbalazi> zs = new ArrayList<>();
        DatabaseBroker d = new DatabaseBroker();
        String id_ambalazeS = txtSifra.getText();
        Long id_ambalaze = Long.parseLong(id_ambalazeS);
        zs = d.ZaduzenjaPoAmbalazai(id_ambalaze);
        ZbirnoStanjePoAmbalaziTableModel zstpm = new ZbirnoStanjePoAmbalaziTableModel(zs);
        tblZaduzenjaPoAmbalazi.setModel(zstpm);
        
    }

    public void setTxtSifra(Long sifra) {
        txtSifra.setText(String.valueOf(sifra));
        txtSifra.setEditable(false);
    }
    

    
}
