/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;
import java.util.List;
import java.util.ArrayList;
import domain.ZbirnoStanje;
import DBBroker.DatabaseBroker;
import Table.ZbirnoStanjeTableModel;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JDialog;

/**
 *
 * @author xMx
 */
public class ZbirnoStanjeDialog extends javax.swing.JDialog {

    /**
     * Creates new form ZbirnoStanje
     */
    public ZbirnoStanjeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblZbirnoStanje = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Zbirno Stanje"));

        tblZbirnoStanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblZbirnoStanje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblZbirnoStanjeKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblZbirnoStanje);

        jLabel1.setText("Zbirno stanje na dan:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblZbirnoStanjeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblZbirnoStanjeKeyPressed
       tblZbirnoStanje.requestFocus();
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           int selectedRow = tblZbirnoStanje.getSelectedRow();
           if(selectedRow != -1){
               Long id_ambalaze = (Long) tblZbirnoStanje.getValueAt(selectedRow, 0);
               String naziv_ambalaza = (String) tblZbirnoStanje.getValueAt(selectedRow, 1);
               
               
               ZaduzenjaPoAmbalazi dialog = new ZaduzenjaPoAmbalazi(this, true,id_ambalaze,naziv_ambalaza);
               dialog.setTxtNazivAmbalaze(naziv_ambalaza);
               dialog.setTxtSifra(id_ambalaze);
               this.dispose();
               
               
           dialog.setLocationRelativeTo(null);
           dialog.setVisible(true);
           }
           
           
       }
    }//GEN-LAST:event_tblZbirnoStanjeKeyPressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblZbirnoStanje;
    private javax.swing.JTextField txtDatum;
    // End of variables declaration//GEN-END:variables
    private void prepareView(){
        popuniTabelu();
        postaviDatum();
    }
    private void popuniTabelu(){
        List<ZbirnoStanje> zb = new ArrayList<>();
        DatabaseBroker d=  new DatabaseBroker();
        zb = d.ZbirnoStanje();
        ZbirnoStanjeTableModel zstm = new ZbirnoStanjeTableModel(zb);
        tblZbirnoStanje.setModel(zstm);
    }
    
    private void postaviDatum(){
        LocalDate datum = LocalDate.now();
        String datumS = datum.format(DateTimeFormatter.ofPattern("dd-MM-YYYY"));
        txtDatum.setText(datumS);
        txtDatum.setEditable(false);
    }
}
